services:
  - type: web
    name: owasp-bookshop
    image: ipsalmy/graphql:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: owasp_graphql_db
          property: connectionString
    healthCheckPath: /
    port: 10000
